import Card from "./Card";

interface GlossaryEntry {
  term: string;
  definition: string;
}

const ENTRIES: GlossaryEntry[] = [
  {
    term: "TTM",
    definition:
      "Trailing Twelve Months. The most recent 12 months of results, updated every quarter.",
  },
  {
    term: "FY",
    definition:
      "Fiscal Year. A full reported year as defined by the company (not always Jan-Dec).",
  },
  {
    term: "YoY",
    definition:
      "Year-over-Year. Change compared to the same period one year earlier.",
  },
  {
    term: "EPS",
    definition:
      "Earnings Per Share. Net income divided by the number of shares outstanding.",
  },
  {
    term: "FCF",
    definition:
      "Free Cash Flow. Cash generated by the business after reinvesting in its operations.",
  },
  {
    term: "CAGR",
    definition:
      "Compound Annual Growth Rate. The smoothed yearly growth rate that would take you from the starting value to the ending value over N years.",
  },
  {
    term: "P/E",
    definition:
      "Price-to-Earnings. Share price divided by earnings per share. How many dollars the market is paying for each dollar of profit.",
  },
  {
    term: "P/S",
    definition:
      "Price-to-Sales. Market cap divided by revenue. How many dollars the market is paying for each dollar of sales.",
  },
  {
    term: "Year-5 P/E",
    definition:
      "The P/E ratio we assume the market will apply to earnings at the end of the 5-year forecast horizon.",
  },
];

export default function Glossary() {
  return (
    <Card eyebrow="Reference" title="Glossary">
      <dl className="space-y-4">
        {ENTRIES.map((entry) => (
          <div key={entry.term}>
            <dt className="text-sm font-mono font-medium text-[color:var(--accent-2)]">
              {entry.term}
            </dt>
            <dd className="text-xs leading-relaxed text-[color:var(--muted-strong)] mt-0.5">
              {entry.definition}
            </dd>
          </div>
        ))}
      </dl>
    </Card>
  );
}
